{
  "asctime": "2021-01-05 23:26:09,138",
  "levelname": "ERROR",
  "message": "internal server error",
  "funcName": "returned_error_status_flask",
  "filename": "auxiliaries.py",
  "lineno": 396,
  "name": "shared",
  "app_name": "Lightlytics",
  "environment": "prod",
  "module": "auxiliaries",
  "customer_id": null,
  "user_id": null,
  "exc_info": "Traceback (most recent call last):\n  File \"main.py\", line 461, in decode_manage_token\n    response = TokenHandler().decode_manage_token_api(**flask.request.json)\n  File \"../shared/common.py\", line 8, in __call__\n    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)\n  File \"../ms_customers/token_handler.py\", line 29, in __init__\n    self.token_collection = MongoDB('lightlytics', MongoCollections.TOKENS)\n  File \"../shared/mongo_db.py\", line 50, in __init__\n    mongo_connection = self._get_mongodb_connection_params()\n  File \"../shared/mongo_db.py\", line 62, in _get_mongodb_connection_params\n    mongo_username = os.getenv('SECRET_MONGO_USERNAME', config_file['MongoDB'].get('User'))\nKeyError: 'MongoDB'",
  "version": {
    "build_number": "935",
    "branch": "master",
    "date": "<function get_timestamp at 0x7fb2776c6310>"
  },
  "release_name": "prod"
}